
- name: rabbitmq setup apt
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present


- name: rabbitmq setup apt key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present validate_certs=no


- name: rabbitmq install
  apt: pkg=rabbitmq-server state=installed update-cache=yes
  tags:
    - install
    - update

- name: rabbitmq vhost
  shell: sudo rabbitmqctl add_vhost {{hostname}}
  ignore_errors: on

- name: rabbitmq vhost permissions
  shell: rabbitmqctl set_permissions -p {{hostname}} guest ".*" ".*" ".*"
